### ISSUE TITLE
Group separator setting value may get lost

### ISSUE THREAD

**Issue by tingsu** [physphil/UnitConverterUltimate#201] opened 2020-04-29 17:10 UTC
Hi @physphil ,

Thanks for developping this app. My testing tool found an issue that leads to group separator setting value lost.

The issue was found in the latest released version on Google Play (v.5.6), also in v6.0 and a recent previous version v5.5.1.  I searched this issue history, and found a related issue #101. But the issue I reported here is different w.r.t the issue manifestations.

Reproducing Video
- When I fresh start the app, by default it uses system language (``English`` in my case), we can see the ``None`` option in ``Group Separator`` was initially selected.
- However, when I did some slight manipulations: (1) switch to another language,  (2) select the ``None`` option in ``Group Separator``, and (3) switch back to ``English`` or any other language. We can see wierd ``G`` symbols in the numbers, and we can also see the "None" option was unselected (lost). **Note that this issue cannot be manifested without step (2)**.

Hope to see this issue could be fixed soon :)

![unitconverter_issue_](https://user-images.githubusercontent.com/3156978/80625096-f9201b80-8a4c-11ea-803a-7594cd821cf7.gif)

**Comment by tingsu** [comment] 2020-05-01 07:22
Hi @physphil , can I know your comment on this issue? Thanks.

**Comment by junior291492659** [comment] 2020-05-02 21:41
Hello, thanks for your amazing app and I have also encountered this issue. It would be really appreciated to get your concern on this.

**Comment by tingsu** [comment] 2020-05-07 06:55
Any update on this issue?

**Comment by physphil** [comment] 2020-05-09 13:19
Yikes, that's no good 😬. Thanks for reporting it. I know the cause of this bug and it shouldn't be too difficult to fix, I've just got to find a bit of time to do so. Hopefully I'll have it fixed int he next couple of weeks 🙂

**Comment by tingsu** [comment] 2020-05-09 13:22
Thanks for your quick reply and confirmation, @physphil!  I can help on validating the fix later :)

**Comment by physphil** [comment] 2020-05-09 19:10
Will be fixed when #202 merges.

**Comment by physphil** [comment] 2020-05-09 19:14
@tingsu If you're able to verify the fix works for you on the branch in #202 that would be great!

**Comment by tingsu** [comment] 2020-05-09 19:20
@physphil No problem. I will let you know soon.

**Comment by tingsu** [comment] 2020-05-10 06:07
Hi @physphil, the issue was fixed by #202. You can go ahead to merge it into the master. Thanks for your fix!

**Closed** 2020-05-10 12:21 UTC
